name: pubdev_notifier
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  cloud_firestore: ^3.4.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.5.0
  firebase_core: ^1.20.0
  firebase_messaging: ^12.0.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_launcher_icons: ^0.9.3
  flutter_riverpod: ^2.0.0-dev.9
  flutterfire_ui: ^0.4.3
  font_awesome_flutter: ^10.1.0
  go_router: ^4.0.0
  heroicons: ^0.5.0
  hooks_riverpod: ^2.0.0-dev.9
  rename: ^2.0.1
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - "assets/pubdev_icon.png"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/pubdev_icon.png"
