name: pubdev_notifier
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  cloud_firestore: ^3.2.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.4.1
  firebase_core: ^1.19.1
  firebase_messaging: ^11.4.4
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_launcher_icons: ^0.9.3
  flutter_riverpod: ^2.0.0-dev.9
  go_router: ^4.0.0
  heroicons: ^0.5.0
  rename: ^2.0.1
  url_launcher: ^6.1.4

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/pubdev_icon.png"
