// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChB0-LB5lQiqcUZIStNVTH5F7HEjQoaG4',
    appId: '1:805782479126:android:e4b07c482878973f987037',
    messagingSenderId: '805782479126',
    projectId: 'pubdev-notifier',
    storageBucket: 'pubdev-notifier.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApcvtMwj5QekjA42_Uja-k4VvJxOH89Gk',
    appId: '1:805782479126:ios:8f9adf78d74bfebe987037',
    messagingSenderId: '805782479126',
    projectId: 'pubdev-notifier',
    storageBucket: 'pubdev-notifier.appspot.com',
    iosClientId: '805782479126-pttsrf4ctpt07tqocfs8e0v2b562e9gv.apps.googleusercontent.com',
    iosBundleId: 'com.pubdevNotifier.release',
  );
}
